server:
  port: 8089

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zcj
      username: root
      password: Root_123
  mvc:
    view:
      prefix: /
      suffix: .html
#mybatis配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/com/banyuan/pangu/tank/mapper/*.xml
  type-aliases-package: com.banyuan.pangu.tank.mapper